/* AUTO-GENERATED by chem_ml/cfd/mechanism.py -- do not hand-edit.
 * Source: Phase 4 posterior-mean parameters (Tomasini reproduction).
 * Regenerate with: python -m chem_ml.cli export-mechanism --form udf
 *
 * ADAPT: the exact function signature/registration CFD-ACE+ expects for a
 * user surface-reaction subroutine (see your license's User Subroutines
 * manual). The arithmetic below is exact regardless of that wrapper -- it
 * is a literal C transcription of chem_ml/physics_core.py:gr_logmodel /
 * ge_logmodel evaluated at the Phase 4 posterior mean. Units: pressures are
 * DIMENSIONLESS ratios p_i/p_DCS (Tomasini's own normalization convention,
 * see schema.py); T_wall_K is the LOCAL wall temperature CFD-ACE+ computes,
 * not a setpoint. GR is returned in nm/min (Tomasini's native unit) --
 * convert to your solver's deposition-flux units (e.g. mol/m^2/s) using the
 * SiGe molar volume before wiring into the species/energy source term.
 */
#include <math.h>

/* Standardized-1/T scaler from the fit -- MUST match the value baked in
   here (mu=0.00104333196, sd=6.105412345e-05); it is NOT re-derivable from T alone. */
static const double INV_T_MU = 0.00104333196;
static const double INV_T_SD = 6.105412345e-05;

/* Growth rate power law (Phase 4, DS1 fit). Returns GR in nm/min. */
double calibrated_GR_nm_min(double T_wall_K, double p_HCl_over_pDCS, double p_GeH4_over_pDCS) {
    const double lnK_GR     = 6.399306223;
    const double kappa_GR   = -1.494795145;   /* coefficient of STANDARDIZED 1/T */
    const double gamma_HCl  = -0.7097438995;
    const double gamma_GeH4 = 1.310385586;

    double invT_std = (1.0 / T_wall_K - INV_T_MU) / INV_T_SD;
    double ln_GR = lnK_GR
        + kappa_GR   * invT_std
        + gamma_HCl  * log(p_HCl_over_pDCS)
        + gamma_GeH4 * log(p_GeH4_over_pDCS);
    return exp(ln_GR);
}

/* Ge atomic fraction power law (Phase 4, DS1 fit). Returns x_Ge in [0,1]. */
double calibrated_xGe(double T_wall_K, double p_HCl_over_pDCS, double p_GeH4_over_pDCS) {
    const double lnK_Ge      = 0.6568328168;
    const double kappa_Ge    = 0.2632840336;
    const double dgamma_HCl  = 0.1029914986;
    const double dgamma_GeH4 = 0.5108866244;

    double invT_std = (1.0 / T_wall_K - INV_T_MU) / INV_T_SD;
    double ln_ratio = lnK_Ge
        + kappa_Ge    * invT_std
        + dgamma_HCl  * log(p_HCl_over_pDCS)
        + dgamma_GeH4 * log(p_GeH4_over_pDCS);
    double ratio = exp(ln_ratio);       /* x/(1-x) */
    return ratio / (1.0 + ratio);       /* -> x */
}
