"""
CFD-ACE+ input deck writer / output parser (Phase 9.4.1/9.4.2).

We have no CFD-ACE+ license/output in this environment, so two things are
true about this module and must stay true for anyone editing it:
  1. `write_cfd_deck` writes a STRUCTURED, HUMAN-READABLE deck in a generic
     keyword=value format, not CFD-ACE+'s actual proprietary .DTF binary/
     text format (which is undocumented to this codebase). Treat it as a
     structured specification of every input CFD-ACE+ needs, to be
     transcribed into the real GUI/DTF by whoever runs the job.
  2. `parse_cfd_output` defines and parses a CONTRACT (a CSV schema) for
     what we need back, not a parser for CFD-ACE+'s real output format
     (which is also undocumented here). Give this schema to whoever runs
     the CFD job as the deliverable format, or write a small adapter that
     converts CFD-ACE+'s native output into it.
"""
from __future__ import annotations

import csv
import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

log = logging.getLogger("chem_ml")


@dataclass
class CFDCondition:
    T_set_K: float
    flows_sccm: dict            # {'DCS':.., 'GeH4':.., 'HCl':.., 'B2H6':..}
    P_tot_torr: float
    geometry_id: str
    condition_id: str = ""       # unique run label; defaults to a hash of the above


@dataclass
class CFDResult:
    condition: CFDCondition
    r_mm: np.ndarray             # radial coordinate across the wafer
    surface_T_K: np.ndarray      # local wall T(r) -- may differ from T_set_K
    surface_p_i: dict            # {'HCl': p_HCl(r)/p_DCS(r), 'GeH4': ..., ...} local ratios at the wafer
    GR_profile_nm_min: np.ndarray
    Ge_profile_frac: np.ndarray


_DECK_TEMPLATE = """\
# CFD-ACE+ INPUT SPECIFICATION (generic structured form -- see module
# docstring: transcribe into the actual GUI/.DTF model file).
# Generated by chem_ml.cfd.io.write_cfd_deck for condition_id={condition_id}

[GEOMETRY]
geometry_id = {geometry_id}

[BOUNDARY_CONDITIONS.INLET]
T_set_K = {T_set_K}
P_tot_torr = {P_tot_torr}
{flow_lines}

[BOUNDARY_CONDITIONS.WAFER_SURFACE]
# Surface reaction BC: point this at either
#   (a) the generated UDF (surface_bc_udf.c, RECOMMENDED -- exact calibrated
#       chemistry, see cfd/mechanism.py), or
#   (b) the elementary_mechanism.json deck as a standard surface-reaction
#       card set (lossy re-derivation, see mechanism.py docstring for what
#       is/isn't calibrated in that form).
surface_bc_type = user_subroutine  # or "surface_reaction_mechanism"
surface_bc_source = surface_bc_udf.c  # or elementary_mechanism.json

[SOLVER]
model = laminar_flow + species_transport + energy + surface_chemistry
steady_state = true

[OUTPUT_CONTRACT]
# Whatever post-processes the raw CFD-ACE+ output MUST emit a CSV matching
# parse_cfd_output's schema (see that function's docstring) for this
# condition_id -- that's the only requirement this pipeline places on the
# CFD side.
expected_output_csv = {condition_id}_wafer_profile.csv
"""


def write_cfd_deck(cond: CFDCondition, path: str | Path) -> Path:
    """Write the structured input specification for one CFDCondition.
    See module docstring: this is a specification to transcribe into
    CFD-ACE+'s real input mechanism, not that format itself."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    flow_lines = "\n".join(f"flow_{species}_sccm = {sccm}" for species, sccm in cond.flows_sccm.items())
    condition_id = cond.condition_id or _default_condition_id(cond)
    deck = _DECK_TEMPLATE.format(
        condition_id=condition_id, geometry_id=cond.geometry_id,
        T_set_K=cond.T_set_K, P_tot_torr=cond.P_tot_torr, flow_lines=flow_lines,
    )
    path.write_text(deck)
    log.info("Wrote CFD input specification to %s (condition_id=%s)", path, condition_id)
    return path


def _default_condition_id(cond: CFDCondition) -> str:
    flow_str = "_".join(f"{k}{v:g}" for k, v in sorted(cond.flows_sccm.items()))
    return f"T{cond.T_set_K:.0f}K_P{cond.P_tot_torr:g}Torr_{flow_str}"


# ---------------------------------------------------------------------------
# OUTPUT CONTRACT: a wafer radial profile CSV with these exact columns.
# Whoever runs the actual CFD-ACE+ job must produce this (or a thin adapter
# script converting CFD-ACE+'s native post-processor export into it).
# ---------------------------------------------------------------------------
_OUTPUT_COLUMNS = ["r_mm", "surface_T_K", "p_HCl_over_pDCS", "p_GeH4_over_pDCS",
                   "p_B2H6_over_pDCS", "GR_nm_min", "Ge_frac"]


def write_output_contract_template(path: str | Path) -> Path:
    """Write an empty CSV with the exact header parse_cfd_output expects,
    as a fillable template to hand to whoever runs the CFD job."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        csv.writer(f).writerow(_OUTPUT_COLUMNS)
    return path


def parse_cfd_output(path: str | Path, condition: CFDCondition) -> CFDResult:
    """Parse a wafer radial-profile CSV matching _OUTPUT_COLUMNS into a
    CFDResult. This is the CONTRACT this pipeline needs from CFD-ACE+, not
    a parser for its native output -- see module docstring."""
    path = Path(path)
    rows = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        missing = set(_OUTPUT_COLUMNS) - set(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"{path} is missing required columns {missing}. "
                f"Expected header: {_OUTPUT_COLUMNS} (see cfd/io.py OUTPUT_CONTRACT)."
            )
        rows = list(reader)
    if not rows:
        raise ValueError(f"{path} has no data rows")

    arr = {c: np.array([float(r[c]) for r in rows]) for c in _OUTPUT_COLUMNS}
    return CFDResult(
        condition=condition,
        r_mm=arr["r_mm"],
        surface_T_K=arr["surface_T_K"],
        surface_p_i={"HCl": arr["p_HCl_over_pDCS"], "GeH4": arr["p_GeH4_over_pDCS"],
                    "B2H6": arr["p_B2H6_over_pDCS"]},
        GR_profile_nm_min=arr["GR_nm_min"],
        Ge_profile_frac=arr["Ge_frac"],
    )
