/* AUTO-GENERATED by chem_ml/cfd/mechanism.py -- do not hand-edit.
 * chem_system='silane': NO calibrated power-law UDF exists for this
 * system -- Tomasini's data (which chem_ml/physics_core.py's gr_logmodel/
 * ge_logmodel are fit to) is 100% DCS-based, so there is nothing to
 * transcribe here. Use elementary_mechanism.json's literature-seed steps
 * as CFD-ACE+'s surface-reaction mechanism input instead (all steps
 * status="seed", not data-calibrated -- see that file's
 * calibration_status field). To get a calibrated UDF for this system,
 * first run a DS1-shaped experimental sweep with this precursor and
 * fit chem_ml.physics_core's power law against it (Phase 1-4's method
 * applies to any Si-source precursor, not just DCS).
 */
